name: Django cicd

on:
  push:
    branches: [main]
jobs:
  testing:
    runs-on: ubuntu-latest
    env:
      PG_NAME: ${{ secrets.PG_NAME }}
      PG_USER: ${{ secrets.PG_USER }}
      PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
      PG_HOST: ${{ secrets.PG_HOST }}
      PG_PORT: ${{ secrets.PG_PORT }}

    steps:
      - name: Проверка изменений
        uses: actions/checkout@v2

      - name: Установка python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Command
        run: ls -la
